import { NostrEvent, NostrEventSignedOpened, NostrSpasmEvent, NostrSpasmEventSignedOpened, DmpEvent, Post, DmpEventSignedClosed, DmpEventSignedOpened, SpasmEvent, SpasmEventSigned } from "./../types/interfaces";
export declare const validDmpEvent: DmpEvent;
export declare const validDmpEventSignedClosed: DmpEventSignedClosed;
export declare const validDmpEventSignedOpened: DmpEventSignedOpened;
export declare const validNostrReplyToDmpEvent: NostrSpasmEventSignedOpened;
export declare const validPostWithNostrReplyToDmpEvent: Post;
export declare const validPostWithDmpEventSignedClosed: Post;
export declare const validDmpEventConvertedToSpasm: SpasmEvent;
export declare const validDmpEventSignedClosedConvertedToSpasm: SpasmEventSigned;
export declare const validDmpEventSignedOpenedConvertedToSpasm: SpasmEventSigned;
export declare const validPostWithDmpEventSignedClosedConvertedToSpasm: SpasmEventSigned;
export declare const validNostrEvent: NostrEvent;
export declare const validNostrSpasmEvent: NostrSpasmEvent;
export declare const validNostrEventSignedOpened: NostrEventSignedOpened;
export declare const validNostrSpasmEventSignedOpened: NostrSpasmEventSignedOpened;
export declare const validPostWithNostrEventSignedOpened: {
    id: number;
    target: string;
    action: string;
    title: string;
    text: string;
    signer: string;
    signed_message: string;
    signature: string;
    signed_time: number;
    added_time: string;
    category: any;
    tags: any;
    tickers: any;
    upvote: number;
    downvote: number;
    bullish: number;
    bearish: number;
    important: number;
    scam: number;
    comments_count: number;
    latest_action_added_time: string;
};
export declare const validPostWithNostrSpasmEventSignedOpened: Post;
export declare const validNostrEventConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validNostrSpasmEventConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validNostrEventSignedOpenedConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validNostrSpasmEventSignedOpenedConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validPostWithNostrEventSignedOpenedConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validPostWithNostrSpasmEventSignedOpenedConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validNostrReplyToDmpEventConvertedToSpasmV1_0_0: SpasmEvent;
export declare const validPostWithRssItem: Post;
export declare const validPostWithRssItemConvertedToSpasmV1_0_0: SpasmEvent;
//# sourceMappingURL=_events-data.d.ts.map